name: Python CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest  # Указываем операционную систему для тестов

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3  # Шаг для клонирования репозитория

    - name: Set up Python 3.8
      uses: actions/setup-python@v4  # Шаг для настройки Python
      with:
        python-version: '3.8'  # Указываем версию Python

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip  # Обновление pip
        pip install -r requirements.txt  # Установка зависимостей из requirements.txt

    - name: Set PYTHONPATH
      run: |
        echo "PYTHONPATH=$PYTHONPATH:$(pwd)" >> $GITHUB_ENV  # Настройка PYTHONPATH для правильного импорта

    - name: Run tests and generate report
      run: |
        pytest --html=report.html --self-contained-html  # Запуск тестов и генерация отчета в HTML формате

    - name: Upload test report
      uses: actions/upload-artifact@v3  # Загружаем отчет как артефакт
      with:
        name: test-report
        path: report.html  # Путь к отчету

